name = "32ba-net"
pages_build_output_dir = "public"
compatibility_date = "2024-08-30"

[vars]
GO_VERSION = "1.23.0"
HUGO_VERSION = "0.133.1"
TZ = "Asia/Tokyo"

[env.production.vars]
GO_VERSION = "1.23.0"
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"
HUGO_VERSION = "0.133.1"
TZ = "Asia/Tokyo"
